"""VIDEX domain package."""

from videx.domain.schemas import (
    AudioMetadata,
    AudioSegment,
    BoundingBox,
    CoordinateType,
    Detection,
    Event,
    EventType,
    Evidence,
    EvidenceType,
    Frame,
    FrameTimestamp,
    OCRObservation,
    RawOCRObservation,
    Scene,
    SoundObservation,
    TextObservation,
    TimestampSource,
    Track,
    TrackStatus,
    TrajectoryPoint,
    TranscriptSegment,
    Video,
    VideoManifest,
    WordTimestamp,
)

__all__ = [
    "AudioMetadata",
    "AudioSegment",
    "BoundingBox",
    "CoordinateType",
    "Detection",
    "Event",
    "EventType",
    "Evidence",
    "EvidenceType",
    "Frame",
    "FrameTimestamp",
    "OCRObservation",
    "RawOCRObservation",
    "Scene",
    "SoundObservation",
    "TextObservation",
    "TimestampSource",
    "Track",
    "TrackStatus",
    "TrajectoryPoint",
    "TranscriptSegment",
    "Video",
    "VideoManifest",
    "WordTimestamp",
]
